export const generalVocab = [
    // === A2: Daily Life ===
    { dutch: "Huis", english: "House", level: "A2", category: "Home", explanation: "A building in which people live.", example: "Ik woon in een klein huis." },
    { dutch: "Keuken", english: "Kitchen", level: "A2", category: "Home", explanation: "The room where cooking is done.", example: "De keuken is naast de woonkamer." },
    { dutch: "Slaapkamer", english: "Bedroom", level: "A2", category: "Home", explanation: "A room used for sleeping.", example: "Mijn slaapkamer is groot en licht." },
    { dutch: "Badkamer", english: "Bathroom", level: "A2", category: "Home", explanation: "A room with a bath or shower, toilet, and sink.", example: "Ik douche elke ochtend in de badkamer." },
    { dutch: "Woonkamer", english: "Living room", level: "A2", category: "Home", explanation: "The main room in a house where people relax.", example: "We zitten in de woonkamer te kijken." },
    { dutch: "Tuin", english: "Garden", level: "A2", category: "Home", explanation: "An outdoor space with plants and flowers.", example: "In de zomer eten we buiten in de tuin." },
    { dutch: "Tafel", english: "Table", level: "A2", category: "Home", explanation: "A flat surface raised on legs, used for eating or working.", example: "De tafel staat in de keuken." },
    { dutch: "Stoel", english: "Chair", level: "A2", category: "Home", explanation: "A separate seat for one person.", example: "Ga zitten op die stoel." },
    { dutch: "Bed", english: "Bed", level: "A2", category: "Home", explanation: "A piece of furniture for sleeping.", example: "Ik ga vroeg naar bed vanavond." },
    { dutch: "Lamp", english: "Lamp", level: "A2", category: "Home", explanation: "A device that gives light.", example: "De lamp in de kamer is kapot." },
    { dutch: "Raam", english: "Window", level: "A2", category: "Home", explanation: "An opening in a wall or roof fitted with glass.", example: "Doe het raam dicht, het is koud." },
    { dutch: "Deur", english: "Door", level: "A2", category: "Home", explanation: "A hinged barrier used to close an entrance.", example: "Sluit de deur als je weggaat." },

    // === A2: Food & Drink ===
    { dutch: "Brood", english: "Bread", level: "A2", category: "Food & Drink", explanation: "A staple food made of flour and water, baked.", example: "Ik eet elke ochtend brood met kaas." },
    { dutch: "Kaas", english: "Cheese", level: "A2", category: "Food & Drink", explanation: "A food made from pressed milk curds.", example: "Gouda kaas is heel lekker." },
    { dutch: "Melk", english: "Milk", level: "A2", category: "Food & Drink", explanation: "A white drink produced by cows.", example: "Ik drink elke dag melk." },
    { dutch: "Koffie", english: "Coffee", level: "A2", category: "Food & Drink", explanation: "A hot drink made from roasted coffee beans.", example: "Wilt u koffie of thee?" },
    { dutch: "Thee", english: "Tea", level: "A2", category: "Food & Drink", explanation: "A hot drink made by infusing tea leaves.", example: "Ik drink 's avonds graag thee." },
    { dutch: "Water", english: "Water", level: "A2", category: "Food & Drink", explanation: "A clear, colourless, odourless liquid.", example: "Mag ik een glas water?" },
    { dutch: "Appel", english: "Apple", level: "A2", category: "Food & Drink", explanation: "A round fruit with red, green, or yellow skin.", example: "Een appel per dag houdt de dokter weg." },
    { dutch: "Groenten", english: "Vegetables", level: "A2", category: "Food & Drink", explanation: "Plants or parts of plants used as food.", example: "Eet elke dag genoeg groenten." },
    { dutch: "Fruit", english: "Fruit", level: "A2", category: "Food & Drink", explanation: "The sweet, fleshy product of a tree or other plant.", example: "Vers fruit is gezond en lekker." },
    { dutch: "Vlees", english: "Meat", level: "A2", category: "Food & Drink", explanation: "The flesh of an animal, used as food.", example: "Zij eet geen vlees, ze is vegetarisch." },
    { dutch: "Soep", english: "Soup", level: "A2", category: "Food & Drink", explanation: "A liquid dish made by boiling meat, vegetables.", example: "Een warme soep is lekker in de winter." },
    { dutch: "Rijst", english: "Rice", level: "A2", category: "Food & Drink", explanation: "A starchy grain cooked and eaten as a staple food.", example: "Vanavond eten we rijst met kip." },
    { dutch: "Aardappel", english: "Potato", level: "A2", category: "Food & Drink", explanation: "A starchy plant tuber cooked as a vegetable.", example: "We eten vanavond aardappelen met groenten." },

    // === A2: Family ===
    { dutch: "Familie", english: "Family", level: "A2", category: "Family", explanation: "A group of people related by blood, marriage, or adoption.", example: "Mijn familie woont in Amsterdam." },
    { dutch: "Moeder", english: "Mother", level: "A2", category: "Family", explanation: "A female parent.", example: "Mijn moeder werkt als lerares." },
    { dutch: "Vader", english: "Father", level: "A2", category: "Family", explanation: "A male parent.", example: "Mijn vader is kok." },
    { dutch: "Kind", english: "Child", level: "A2", category: "Family", explanation: "A young human being.", example: "Het kind speelt in de tuin." },
    { dutch: "Kinderen", english: "Children", level: "A2", category: "Family", explanation: "More than one young human being.", example: "Ze hebben twee kinderen." },
    { dutch: "Broer", english: "Brother", level: "A2", category: "Family", explanation: "A male who has the same parents as you.", example: "Mijn broer is drie jaar ouder dan ik." },
    { dutch: "Zus", english: "Sister", level: "A2", category: "Family", explanation: "A female who has the same parents as you.", example: "Mijn zus woont in Rotterdam." },
    { dutch: "Opa", english: "Grandfather", level: "A2", category: "Family", explanation: "The father of one's father or mother.", example: "Mijn opa vertelt altijd mooie verhalen." },
    { dutch: "Oma", english: "Grandmother", level: "A2", category: "Family", explanation: "The mother of one's father or mother.", example: "Oma bakt de lekkerste koekjes." },
    { dutch: "Echtgenoot", english: "Husband", level: "A2", category: "Family", explanation: "A married man considered in relation to his wife.", example: "Haar echtgenoot werkt bij een bank." },
    { dutch: "Echtgenote", english: "Wife", level: "A2", category: "Family", explanation: "A married woman considered in relation to her husband.", example: "Zijn echtgenote is lerares." },

    // === A2: Time ===
    { dutch: "Gisteren", english: "Yesterday", level: "A2", category: "Time", explanation: "The day before today.", example: "Gisteren ben ik naar de markt geweest." },
    { dutch: "Vandaag", english: "Today", level: "A2", category: "Time", explanation: "On this day.", example: "Vandaag heb ik vrij." },
    { dutch: "Morgen", english: "Tomorrow", level: "A2", category: "Time", explanation: "The day after today.", example: "Morgen ga ik naar school." },
    { dutch: "Week", english: "Week", level: "A2", category: "Time", explanation: "A period of seven days.", example: "Volgende week ga ik op vakantie." },
    { dutch: "Maand", english: "Month", level: "A2", category: "Time", explanation: "One of the twelve periods into which a year is divided.", example: "Deze maand is het mijn verjaardag." },
    { dutch: "Jaar", english: "Year", level: "A2", category: "Time", explanation: "A period of 365 days.", example: "Dit jaar leer ik Nederlands." },
    { dutch: "Ochtend", english: "Morning", level: "A2", category: "Time", explanation: "The early part of the day.", example: "Elke ochtend drink ik koffie." },
    { dutch: "Middag", english: "Afternoon", level: "A2", category: "Time", explanation: "The time from noon to evening.", example: "In de middag ga ik winkelen." },
    { dutch: "Avond", english: "Evening", level: "A2", category: "Time", explanation: "The period from late afternoon to bedtime.", example: "'s Avonds kijk ik televisie." },
    { dutch: "Nacht", english: "Night", level: "A2", category: "Time", explanation: "The period from sunset to sunrise.", example: "In de nacht is het stil buiten." },

    // === A2: Transport ===
    { dutch: "Fiets", english: "Bicycle", level: "A2", category: "Transport", explanation: "A vehicle with two wheels, propelled by pedalling.", example: "Ik ga elke dag met de fiets naar mijn werk." },
    { dutch: "Auto", english: "Car", level: "A2", category: "Transport", explanation: "A road vehicle powered by an engine.", example: "Mijn auto staat voor de deur." },
    { dutch: "Bus", english: "Bus", level: "A2", category: "Transport", explanation: "A large motor vehicle for passengers.", example: "Ik neem de bus naar het station." },
    { dutch: "Trein", english: "Train", level: "A2", category: "Transport", explanation: "A series of connected rail carriages.", example: "De trein naar Amsterdam vertrekt om 9 uur." },
    { dutch: "Tram", english: "Tram", level: "A2", category: "Transport", explanation: "A rail vehicle that runs on city streets.", example: "Neem lijn 5 met de tram." },
    { dutch: "Station", english: "Station", level: "A2", category: "Transport", explanation: "A place where trains or buses stop.", example: "Het treinstation is vlakbij." },
    { dutch: "Vliegtuig", english: "Plane", level: "A2", category: "Transport", explanation: "A powered aircraft for transporting passengers.", example: "Het vliegtuig vertrekt om zeven uur." },
    { dutch: "Luchthaven", english: "Airport", level: "A2", category: "Transport", explanation: "A place where aircraft take off and land.", example: "Ik moet vroeg naar de luchthaven." },

    // === A2: Shopping ===
    { dutch: "Supermarkt", english: "Supermarket", level: "A2", category: "Shopping", explanation: "A large self-service shop selling foods and goods.", example: "Ik doe mijn boodschappen bij de supermarkt." },
    { dutch: "Winkel", english: "Shop", level: "A2", category: "Shopping", explanation: "A building or part of a building where goods are sold.", example: "Er is een nieuwe winkel geopend in de straat." },
    { dutch: "Markt", english: "Market", level: "A2", category: "Shopping", explanation: "A regular gathering for buying and selling.", example: "Op zaterdag is er een markt in het centrum." },
    { dutch: "Kassière", english: "Cashier", level: "A2", category: "Shopping", explanation: "A person who takes payments in a shop.", example: "De kassière geeft me het wisselgeld." },
    { dutch: "Prijs", english: "Price", level: "A2", category: "Shopping", explanation: "The amount of money expected for something.", example: "Wat is de prijs van dit product?" },
    { dutch: "Rekening", english: "Bill / Receipt", level: "A2", category: "Shopping", explanation: "A written statement of money owed.", example: "Mag ik de rekening?" },
    { dutch: "Korting", english: "Discount", level: "A2", category: "Shopping", explanation: "A reduction in the usual price.", example: "Er is vandaag 20% korting in de winkel." },
    { dutch: "Boodschappen", english: "Groceries / Errands", level: "A2", category: "Shopping", explanation: "Items bought at a food shop, or tasks to be done.", example: "Ik ga de boodschappen doen." },

    // === A2: Weather ===
    { dutch: "Regen", english: "Rain", level: "A2", category: "Weather", explanation: "Drops of water falling from clouds.", example: "Het regent buiten, neem je paraplu mee." },
    { dutch: "Zon", english: "Sun", level: "A2", category: "Weather", explanation: "The star around which the Earth orbits, giving light.", example: "De zon schijnt vandaag mooi." },
    { dutch: "Wind", english: "Wind", level: "A2", category: "Weather", explanation: "The natural movement of air outdoors.", example: "Er staat een harde wind vandaag." },
    { dutch: "Sneeuw", english: "Snow", level: "A2", category: "Weather", explanation: "Frozen water that falls from the sky in white flakes.", example: "In de winter valt er soms sneeuw." },
    { dutch: "Warm", english: "Warm / Hot", level: "A2", category: "Weather", explanation: "Having a fairly high temperature.", example: "Het is erg warm vandaag, meer dan 30 graden." },
    { dutch: "Koud", english: "Cold", level: "A2", category: "Weather", explanation: "Having a low temperature.", example: "Trek een jas aan, het is koud buiten." },
    { dutch: "Bewolkt", english: "Cloudy", level: "A2", category: "Weather", explanation: "Covered with clouds.", example: "Het is bewolkt maar droog vandaag." },
    { dutch: "Onweer", english: "Thunderstorm", level: "A2", category: "Weather", explanation: "A storm with lightning and thunder.", example: "Vanavond is er onweer voorspeld." },

    // === B1: Work & Education ===
    { dutch: "Werk", english: "Work / Job", level: "B1", category: "Work", explanation: "Activity involving mental or physical effort done in order to achieve a result.", example: "Ik ga morgen vroeg naar mijn werk." },
    { dutch: "Collega", english: "Colleague", level: "B1", category: "Work", explanation: "A person you work alongside.", example: "Mijn collega helpt me altijd goed." },
    { dutch: "Vergadering", english: "Meeting", level: "B1", category: "Work", explanation: "An assembly of people for a particular purpose.", example: "Ik heb om twee uur een vergadering." },
    { dutch: "Kantoor", english: "Office", level: "B1", category: "Work", explanation: "A room where administrative work is done.", example: "Zijn kantoor is op de derde verdieping." },
    { dutch: "Chef", english: "Boss / Manager", level: "B1", category: "Work", explanation: "A person who is in charge of workers.", example: "Mijn chef is streng maar eerlijk." },
    { dutch: "Salaris", english: "Salary", level: "B1", category: "Work", explanation: "A regular payment for employment.", example: "Het salaris word elke maand betaald." },
    { dutch: "Verlof", english: "Leave / Holiday", level: "B1", category: "Work", explanation: "Permission to be absent from work.", example: "Ik heb volgende week verlof." },
    { dutch: "School", english: "School", level: "B1", category: "Education", explanation: "An institution for educating children.", example: "De kinderen gaan elke dag naar school." },
    { dutch: "Leraar", english: "Teacher", level: "B1", category: "Education", explanation: "A person who teaches at school.", example: "De leraar legt de les goed uit." },
    { dutch: "Cursus", english: "Course", level: "B1", category: "Education", explanation: "A series of lessons.", example: "Ik volg een cursus Nederlands." },
    { dutch: "Diploma", english: "Diploma / Certificate", level: "B1", category: "Education", explanation: "A certificate awarded for passing an exam.", example: "Ze heeft haar diploma gehaald." },
    { dutch: "Huiswerk", english: "Homework", level: "B1", category: "Education", explanation: "Schoolwork done at home.", example: "Het kind maakt zijn huiswerk na school." },
    { dutch: "Tentamen", english: "Exam", level: "B1", category: "Education", explanation: "A formal test of knowledge.", example: "Volgende week heb ik een tentamen Nederlands." },

    // === B1: Feelings & Personality ===
    { dutch: "Blij", english: "Happy / Glad", level: "B1", category: "Feelings", explanation: "Feeling pleased or contented.", example: "Ik ben blij dat je bent gekomen." },
    { dutch: "Verdrietig", english: "Sad", level: "B1", category: "Feelings", explanation: "Feeling sorrow or unhappiness.", example: "Ze was verdrietig toen haar kat stierf." },
    { dutch: "Boos", english: "Angry", level: "B1", category: "Feelings", explanation: "Feeling or showing strong annoyance or displeasure.", example: "Hij is boos omdat hij te laat was." },
    { dutch: "Bang", english: "Scared / Afraid", level: "B1", category: "Feelings", explanation: "Feeling fear or anxiety.", example: "Ik ben bang voor onweer." },
    { dutch: "Trots", english: "Proud", level: "B1", category: "Feelings", explanation: "Feeling deep pleasure from one's own achievements.", example: "Ze is trots op haar kind." },
    { dutch: "Zenuwachtig", english: "Nervous", level: "B1", category: "Feelings", explanation: "Easily agitated or alarmed.", example: "Ik ben zenuwachtig voor het examen." },
    { dutch: "Moe", english: "Tired", level: "B1", category: "Feelings", explanation: "In need of sleep or rest.", example: "Na het werk ben ik altijd moe." },
    { dutch: "Gelukkig", english: "Happy / Fortunate", level: "B1", category: "Feelings", explanation: "Feeling or showing pleasure and contentment.", example: "Ik ben heel gelukkig met mijn leven." },
    { dutch: "Teleurgesteld", english: "Disappointed", level: "B1", category: "Feelings", explanation: "Sad because something did not happen as hoped.", example: "Hij was teleurgesteld over zijn resultaat." },

    // === B1: City & Community ===
    { dutch: "Buurt", english: "Neighbourhood", level: "B1", category: "Community", explanation: "A district or area in a town or city.", example: "Wij wonen in een leuke buurt." },
    { dutch: "Straat", english: "Street", level: "B1", category: "Community", explanation: "A public road in a city or town.", example: "De straat is gisteren schoongemaakt." },
    { dutch: "Gemeente", english: "Municipality", level: "B1", category: "Community", explanation: "A local government body.", example: "U kunt een klacht melden bij de gemeente." },
    { dutch: "Bibliotheek", english: "Library", level: "B1", category: "Community", explanation: "A building with collections of books for borrowing.", example: "Ik leen boeken bij de bibliotheek." },
    { dutch: "Postkantoor", english: "Post office", level: "B1", category: "Community", explanation: "A government office handling mail and postal services.", example: "Ik stuur een pakket via het postkantoor." },
    { dutch: "Bank", english: "Bank", level: "B1", category: "Community", explanation: "An institution providing financial services.", example: "Ik haal geld op bij de bank." },
    { dutch: "Politie", english: "Police", level: "B1", category: "Community", explanation: "The civil force responsible for maintaining law and order.", example: "Bel de politie als er iets is." },
    { dutch: "Brandweer", english: "Fire brigade", level: "B1", category: "Community", explanation: "An organisation of trained fire fighters.", example: "De brandweer was er snel bij." },

    // === B1: Hobbies & Leisure ===
    { dutch: "Vakantie", english: "Holiday / Vacation", level: "B1", category: "Leisure", explanation: "A period of time spent away from work or school.", example: "Wij gaan deze zomer op vakantie naar Spanje." },
    { dutch: "Muziek", english: "Music", level: "B1", category: "Leisure", explanation: "Vocal or instrumental sounds combined to produce beauty.", example: "In mijn vrije tijd luister ik graag naar muziek." },
    { dutch: "Sport", english: "Sport", level: "B1", category: "Leisure", explanation: "An activity requiring physical effort and skill.", example: "Sport is goed voor je gezondheid." },
    { dutch: "Voetbal", english: "Football / Soccer", level: "B1", category: "Leisure", explanation: "A team sport played with a round ball.", example: "Op zondag kijkt hij voetbal op televisie." },
    { dutch: "Zwemmen", english: "Swimming", level: "B1", category: "Leisure", explanation: "Propelling the body through water with limbs.", example: "Elke zomervakantie ga ik zwemmen." },
    { dutch: "Lezen", english: "Reading", level: "B1", category: "Leisure", explanation: "Looking at and understanding words or symbols.", example: "In het weekend lees ik graag een boek." },
    { dutch: "Film", english: "Movie / Film", level: "B1", category: "Leisure", explanation: "A sequence of photographs projected onto a screen.", example: "Welke film ga jij vanavond zien?" },
    { dutch: "Reizen", english: "Travelling", level: "B1", category: "Leisure", explanation: "Making a journey to places.", example: "Ze vindt het leuk om te reizen." },
    { dutch: "Wandelen", english: "Walking / Hiking", level: "B1", category: "Leisure", explanation: "Moving at a regular pace on foot.", example: "In het weekend gaan we wandelen in het bos." },
    { dutch: "Koken", english: "Cooking", level: "B1", category: "Leisure", explanation: "Preparing food by heating it.", example: "Ik kook elke avond een warme maaltijd." },

    // === B2: Society & Issues ===
    { dutch: "Milieu", english: "Environment", level: "B2", category: "Society", explanation: "The natural world and the conditions in which people live.", example: "We moeten het milieu beschermen." },
    { dutch: "Politiek", english: "Politics", level: "B2", category: "Society", explanation: "Activities relating to the governance of a country.", example: "Ik volg de politiek graag in het nieuws." },
    { dutch: "Rechten", english: "Rights", level: "B2", category: "Society", explanation: "A moral or legal entitlement to have or do something.", example: "Iedereen heeft gelijke rechten." },
    { dutch: "Armoede", english: "Poverty", level: "B2", category: "Society", explanation: "The state of being extremely poor.", example: "Armoede is een groot probleem in de wereld." },
    { dutch: "Veiligheid", english: "Safety / Security", level: "B2", category: "Society", explanation: "The condition of being protected from danger or harm.", example: "De veiligheid in de wijk is verbeterd." },
    { dutch: "Discriminatie", english: "Discrimination", level: "B2", category: "Society", explanation: "The unfair treatment of different categories of people.", example: "Discriminatie op het werk is niet acceptabel." },
    { dutch: "Gelijkheid", english: "Equality", level: "B2", category: "Society", explanation: "The state of being equal in rights and opportunities.", example: "Gelijkheid tussen mannen en vrouwen is belangrijk." },
    { dutch: "Immigratie", english: "Immigration", level: "B2", category: "Society", explanation: "The action of coming to live permanently in a foreign country.", example: "Immigratie is al eeuwen deel van Nederland." },
    { dutch: "Klimaat", english: "Climate", level: "B2", category: "Society", explanation: "The weather conditions prevailing in an area over a long period.", example: "Het klimaat verandert snel door menselijk handelen." },
    { dutch: "Duurzaamheid", english: "Sustainability", level: "B2", category: "Society", explanation: "The avoidance of natural resource depletion.", example: "Duurzaamheid is een prioriteit voor de gemeente." },

    // === B2: Technology & Media ===
    { dutch: "Computer", english: "Computer", level: "B2", category: "Technology", explanation: "An electronic device for storing and processing data.", example: "Mijn computer is kapot en moet gerepareerd worden." },
    { dutch: "Internet", english: "Internet", level: "B2", category: "Technology", explanation: "A global computer network providing information.", example: "Zonder internet kan ik mijn werk niet doen." },
    { dutch: "Telefoon", english: "Phone", level: "B2", category: "Technology", explanation: "A device for transmitting voice calls.", example: "Mijn telefoon heeft een lege batterij." },
    { dutch: "Social media", english: "Social media", level: "B2", category: "Technology", explanation: "Websites enabling users to create and share content.", example: "Veel jongeren gebruiken social media de hele dag." },
    { dutch: "Nieuws", english: "News", level: "B2", category: "Technology", explanation: "Newly received or noteworthy information about events.", example: "Ik lees elke ochtend het nieuws op mijn telefoon." },
    { dutch: "Software", english: "Software", level: "B2", category: "Technology", explanation: "Programs used by a computer.", example: "De software is bijgewerkt naar de nieuwste versie." },
    { dutch: "App", english: "App", level: "B2", category: "Technology", explanation: "A software application for mobile devices.", example: "Er is een handige app om Nederlands te oefenen." },
    { dutch: "Wachtwoord", english: "Password", level: "B2", category: "Technology", explanation: "A secret word used to gain access to a system.", example: "Vergeet niet uw wachtwoord te veranderen." },

    // === C1: Abstract / Advanced ===
    { dutch: "Samenwerking", english: "Collaboration / Cooperation", level: "C1", category: "Abstract", explanation: "The process of working together to achieve a shared goal.", example: "De samenwerking tussen de twee teams liep heel goed." },
    { dutch: "Verantwoordelijkheid", english: "Responsibility", level: "C1", category: "Abstract", explanation: "The state of having a duty to deal with something.", example: "Hij nam volledige verantwoordelijkheid voor de fout." },
    { dutch: "Onafhankelijkheid", english: "Independence", level: "C1", category: "Abstract", explanation: "The fact or state of being free from outside control.", example: "Onafhankelijkheid is een belangrijk politiek thema." },
    { dutch: "Bereiken", english: "To achieve / To reach", level: "C1", category: "Abstract", explanation: "Successfully bring about something.", example: "Ze heeft haar doelen bereikt na veel hard werken." },
    { dutch: "Invloed", english: "Influence", level: "C1", category: "Abstract", explanation: "The capacity to have an effect on someone's thinking.", example: "De media heeft grote invloed op de samenleving." },
    { dutch: "Begrip", english: "Understanding / Comprehension", level: "C1", category: "Abstract", explanation: "The ability to understand something.", example: "Het begrip van de grammatica is heel belangrijk." },
    { dutch: "Uitdaging", english: "Challenge", level: "C1", category: "Abstract", explanation: "A stimulation and resourcefulness to cope with a task.", example: "Het leren van een nieuwe taal is een uitdaging." },
    { dutch: "Ontwikkeling", english: "Development", level: "C1", category: "Abstract", explanation: "The process of growing or being developed.", example: "De economische ontwikkeling van het land gaat goed." },
    { dutch: "Perspectief", english: "Perspective", level: "C1", category: "Abstract", explanation: "A particular way of viewing something.", example: "We moeten het probleem vanuit een ander perspectief bekijken." },
    { dutch: "Waardering", english: "Appreciation / Gratitude", level: "C1", category: "Abstract", explanation: "Recognition and enjoyment of the good qualities of someone.", example: "Ik heb veel waardering voor zijn inspanning." },

    // === C1: Economy & Finance ===
    { dutch: "Economie", english: "Economy", level: "C1", category: "Finance", explanation: "The state of a country or region in terms of production and consumption.", example: "De economie groeit dit jaar sterk." },
    { dutch: "Belasting", english: "Tax", level: "C1", category: "Finance", explanation: "A compulsory contribution to state revenue.", example: "Iedere burger moet belasting betalen." },
    { dutch: "Begroting", english: "Budget", level: "C1", category: "Finance", explanation: "An estimate of income and expenditure for a set period.", example: "De overheid heeft een nieuwe begroting voorgesteld." },
    { dutch: "Inkomen", english: "Income", level: "C1", category: "Finance", explanation: "Money received, especially on a regular basis.", example: "Zijn inkomen is voldoende om goed van te leven." },
    { dutch: "Schuld", english: "Debt", level: "C1", category: "Finance", explanation: "A sum of money that is owed.", example: "Hij heeft een grote schuld bij de bank." },
    { dutch: "Investering", english: "Investment", level: "C1", category: "Finance", explanation: "The action of investing money for profit.", example: "Een investering in opleiding loont altijd." },
];
